# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-da5vk1u417fc738ri6vg-a.oregon-postgres.render.com:5432/staffchat_db
spring.datasource.username=staffchat_db_user
spring.datasource.password=17zRNQnDPJuJhlXP23bN6vie8GJCCn2A

# Hibernate Settings (Auto-creates tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Settings
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB